name: Publish Single EXE Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish single file EXE
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true `
          /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Create GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/bin/Release/net8.0/win-x64/publish/*.exe
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
